# SPDX-FileCopyrightText: 2025 Famedly GmbH (info@famedly.com)
#
# SPDX-License-Identifier: Apache-2.0

name: Rust

# Trigger the CI on any tags, pushes to any branch and PRs to any branch.
on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["*"]

# Make sure there is no pipeline running uselessly.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Environment variables for all jobs.
env:
  CARGO_TERM_COLOR: always

# Defined CI jobs.
jobs:
  rust:
    uses: famedly/backend-build-workflows/.github/workflows/rust-workflow.yml@v4
    secrets: inherit
    with:
      testcov_args: "--no-tests pass"
  publish:
    needs: rust
    uses: famedly/backend-build-workflows/.github/workflows/publish-crate.yml@v4
    secrets:
      CRATE_REGISTRY_SSH_PRIVKEY: ${{ secrets.CI_SSH_PRIVATE_KEY }}
      CRATE_REGISTRY_AUTH_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
    with:
      crate_registry_name: "crates-io"
      crate_registry_index_url: "https://github.com/rust-lang/crates.io-index"
      packages: "tracing-instrument-mock"
